using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Oracle.ManagedDataAccess.Client;

namespace Appouse.EFCore.ReplicaManager.IntegrationTests;

/// <summary>
/// Oracle's EF Core provider ships no <c>EnableRetryOnFailure</c>, unlike the SQL Server, PostgreSQL
/// and MySQL providers. A retrying strategy therefore has to be supplied by hand, which is exactly
/// what an application wanting transparent replica failover on Oracle must do.
/// </summary>
/// <remarks>
/// <see cref="ReplicaUnavailableException"/> is deliberately excluded: it means every replica was
/// dialled and refused, so retrying cannot help until one comes back. Treating it as transient would
/// only turn a clear error into a slow one.
/// </remarks>
internal sealed class OracleRetryingExecutionStrategy(ExecutionStrategyDependencies dependencies)
    : ExecutionStrategy(dependencies, maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(1))
{
    protected override bool ShouldRetryOn(Exception exception) => exception is not ReplicaUnavailableException;
}

public sealed class OracleCluster : LiveClusterFixture
{
    protected override string Image => "gvenzl/oracle-free:23-slim";

    protected override string Prefix => "armr-ora";

    protected override int BasePort => 55932;

    protected override int ContainerPort => 1521;

    protected override string RunArguments => "-e ORACLE_PASSWORD=pw";

    protected override TimeSpan ReadyTimeout => TimeSpan.FromSeconds(300);

    protected override string QuotedTable => "\"Markers\"";

    protected override string QuotedColumn => "\"Source\"";

    // Oracle has no CREATE TABLE IF NOT EXISTS, and the seeding loop may retry, so the statement is
    // made idempotent by swallowing ORA-00955 (name is already used by an existing object).
    protected override string CreateTableSql =>
        """
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE "Markers" ("Id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Source" NVARCHAR2(200) NOT NULL)';
        EXCEPTION
            WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
        END;
        """;

    public override string ConnectionStringFor(int hostPort)
        => $"User Id=system;Password=pw;Data Source=127.0.0.1:{hostPort}/FREEPDB1;Connection Timeout=5";

    public override DbConnection CreateConnection(string connectionString) => new OracleConnection(connectionString);

    public override void Configure(DbContextOptionsBuilder options, string connectionString)
        => options.UseOracle(connectionString);

    public override void ConfigureWithRetry(DbContextOptionsBuilder options, string connectionString)
        => options.UseOracle(
            connectionString,
            oracle => oracle.ExecutionStrategy(dependencies => new OracleRetryingExecutionStrategy(dependencies)));
}
