using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Appouse.EFCore.ReplicaManager.IntegrationTests;

public sealed class PostgreSqlCluster : LiveClusterFixture
{
    protected override string Image => "postgres:16-alpine";

    protected override string Prefix => "armr-pg";

    protected override int BasePort => 55432;

    protected override int ContainerPort => 5432;

    protected override string RunArguments => "-e POSTGRES_PASSWORD=pw -e POSTGRES_DB=app";

    protected override TimeSpan ReadyTimeout => TimeSpan.FromSeconds(90);

    protected override string QuotedTable => "\"Markers\"";

    protected override string QuotedColumn => "\"Source\"";

    protected override string CreateTableSql =>
        """
        CREATE TABLE IF NOT EXISTS "Markers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Source" text NOT NULL
        )
        """;

    public override string ConnectionStringFor(int hostPort)
        => $"Host=127.0.0.1;Port={hostPort};Database=app;Username=postgres;Password=pw;Timeout=3;Command Timeout=10;Include Error Detail=true";

    public override DbConnection CreateConnection(string connectionString) => new NpgsqlConnection(connectionString);

    public override void Configure(DbContextOptionsBuilder options, string connectionString)
        => options.UseNpgsql(connectionString);

    public override void ConfigureWithRetry(DbContextOptionsBuilder options, string connectionString)
        => options.UseNpgsql(connectionString, npgsql => npgsql.EnableRetryOnFailure(maxRetryCount: 5));
}
